### ISSUE TITLE
Finishing for Alpha version

### ISSUE THREAD

**Issue by Dominux** [Dominux/Pentaract#22]
- [x] Move `init.sql` to startup functionality right in Pentaract backend code
- [x] Move some vars to env
- [x] Choose and set theme for UI
- [x] Create icon, add it as main icon and favicon
- [x] Finally build UI SPA as static inside docker image and make Pentaract server serve it
- [x] Minimize `Dockerfile` as much as possible
- [x] Create CI/CD to build image and push it into the Official Docker Registry
- [x] Add raising error if storage doesn't have storage workers when user tries to use tg API and add endpoint to check it
- [x] Add 404 page to UI
- [x] Add instructions on how to create a storage in storage worker right to UI
- [x] Make comprehensible README.md
